version: '3'
services:
  mon-super-service-back:
    image: labouhiave/tp2
    expose:
      - "8080"
    environment: 
      - ENVIRONMENT=dev
    
  mon-super-service-front:
    image: labouhiave/tp2front
    ports: 
      - "8081:8081"
    build: .
    links:
      - mon-super-service-back
    environment: 
      - APP_PORT=8081
      - WS_BACK_URL=172.17.0.1


